sudo: false
language: python

env:
  global:
  - secure: "..."

after_deploy:
  - git config user.name "K Siva Prasad Reddy"
  - git config user.email "sivaprasadreddy.k@gmail.com"
  - git remote add gh-token "https://${GH_TOKEN}@github.com/sivaprasadreddy/cheatsheets.git";
  - git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
  - pip install mkdocs -U;
  - mkdocs gh-deploy -v --clean --remote-name gh-token;
