site_name: Quick Reference Docs
theme: material
nav:
    - Home: index.md
    - Learning: learning.md
    - Docker: docker.md
    - Ansible: ansible.md
    - Maven: maven.md
    - Linux: linux.md
    
    